"""Defensive cleanup for content generated by Gemini.

`gemini-2.5-flash-lite` (and to a lesser extent the full flash model) sometimes
ignores the "no headers, no markdown bold" instruction and emits structured
sections like:

    **Image Description:**
    A vibrant 4:5 portrait poster…
    **Typography:** …
    ---
    **Instagram Caption:**
    [the actual caption we want]

This module post-processes the model output to:
1. Detect and discard everything before the publishable section if a marker
   like "Caption:", "Post:", "Tweet:", or "Body:" is present.
2. Drop the entire "Image Description" / "Color Palette" / "Typography" /
   "Layout" sections if they appear standalone.
3. Strip markdown bold/italic wrappers (`**x**`, `*x*`, `_x_`) keeping the
   inner text.
4. Trim leading bullet markers (`* `, `- `) on lines that aren't real lists.
5. Remove leading/trailing horizontal-rule separators (`---`, `***`).
"""
from __future__ import annotations

import re

# Section labels that mean "this isn't the content the user wants to publish".
_DESIGN_SECTION_RE = re.compile(
    r"^\s*\*{0,2}\s*(image\s+description|focal\s+point|typography|color\s+palette|"
    r"colour\s+palette|accent\s+elements?|badge|layout|composition|background|"
    r"design\s+notes?|art\s+direction)\s*[:：]\s*\*{0,2}\s*$",
    re.IGNORECASE,
)

# Section labels that indicate the START of the actual post.
_CONTENT_SECTION_RE = re.compile(
    r"^\s*\*{0,2}\s*(?:[\w\s]+?\s)?"
    r"(caption|post|tweet|message|copy|body|article|headline|"
    r"social\s+media\s+caption|instagram\s+caption|linkedin\s+post|"
    r"twitter\s+post|x\s+post|tweet)\s*[:：]\s*\*{0,2}\s*$",
    re.IGNORECASE,
)

_HRULE_RE = re.compile(r"^\s*(?:-{3,}|\*{3,}|_{3,})\s*$")
_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
# A single asterisk pair around at least one non-space char, not at start of line
_ITALIC_RE = re.compile(r"(?<!\*)\*([^\s*][^*]*?)\*(?!\*)")
_UNDERSCORE_RE = re.compile(r"(?<!_)_([^\s_][^_]*?)_(?!_)")
_LEADING_BULLET_RE = re.compile(r"^\s*[*\-]\s+")


def _has_content_marker(lines: list[str]) -> int | None:
    """Return the index of the first 'real content' marker if any."""
    for i, line in enumerate(lines):
        if _CONTENT_SECTION_RE.match(line):
            return i
    return None


def _strip_design_sections(text: str) -> str:
    """Remove design/meta sections (paragraph + content under each label)."""
    lines = text.splitlines()
    out: list[str] = []
    skipping = False
    for line in lines:
        if _DESIGN_SECTION_RE.match(line):
            skipping = True
            continue
        if skipping:
            stripped = line.strip()
            # Stop skipping at the next blank line OR at the next obvious
            # non-design header / start of real content.
            if not stripped:
                skipping = False
                # don't emit the blank line that ended the skipped section
                continue
            if _CONTENT_SECTION_RE.match(line):
                skipping = False
                # fall through and emit nothing for this line; the marker
                # itself is consumed below.
                continue
            # still inside the design section — drop the line
            continue
        out.append(line)
    return "\n".join(out)


def _strip_markdown_emphasis(text: str) -> str:
    text = _BOLD_RE.sub(r"\1", text)
    text = _ITALIC_RE.sub(r"\1", text)
    text = _UNDERSCORE_RE.sub(r"\1", text)
    return text


def _strip_hrules_and_blanks(text: str) -> str:
    lines = [ln for ln in text.splitlines() if not _HRULE_RE.match(ln)]
    # collapse runs of blank lines
    out: list[str] = []
    blank = False
    for ln in lines:
        if not ln.strip():
            if blank:
                continue
            blank = True
            out.append("")
        else:
            blank = False
            out.append(ln)
    return "\n".join(out).strip()


def _drop_leading_bullet_markers(text: str) -> str:
    """If a line starts with '* '/'- ' but the post isn't really a list,
    strip the marker. We keep them when at least 3 consecutive lines look like
    list items (heuristic for real lists)."""
    lines = text.splitlines()
    is_bullet = [bool(_LEADING_BULLET_RE.match(ln)) for ln in lines]
    # find runs
    runs: list[tuple[int, int]] = []
    i = 0
    while i < len(lines):
        if is_bullet[i]:
            j = i
            while j < len(lines) and is_bullet[j]:
                j += 1
            runs.append((i, j))
            i = j
        else:
            i += 1
    keep_run = [False] * len(lines)
    for start, end in runs:
        if end - start >= 3:
            for k in range(start, end):
                keep_run[k] = True
    out = []
    for idx, ln in enumerate(lines):
        if is_bullet[idx] and not keep_run[idx]:
            out.append(_LEADING_BULLET_RE.sub("", ln))
        else:
            out.append(ln)
    return "\n".join(out)


def sanitize_content(text: str) -> str:
    """Run the full cleanup pipeline."""
    if not text:
        return text
    cleaned = text.strip()

    # If the model bracketed the response in ```, strip the fence.
    cleaned = re.sub(r"^```[a-zA-Z]*\n", "", cleaned)
    cleaned = re.sub(r"\n```\s*$", "", cleaned)

    # If a "Caption:" / "Post:" / "Body:" marker exists, take only what
    # follows it — drop any preceding "Image Description"/etc.
    lines = cleaned.splitlines()
    marker_idx = _has_content_marker(lines)
    if marker_idx is not None:
        cleaned = "\n".join(lines[marker_idx + 1 :]).lstrip()

    cleaned = _strip_design_sections(cleaned)
    cleaned = _strip_markdown_emphasis(cleaned)
    cleaned = _drop_leading_bullet_markers(cleaned)
    cleaned = _strip_hrules_and_blanks(cleaned)
    return cleaned
